name: CEPAct Code Quality Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        export PYTHONPATH=.
        pytest

    - name: Lint with pylint
      run: |
        pylint cepact --disable=too-few-public-methods

    - name: Type checking with mypy
      run: |
        mypy cepact --strict
